"""Initial migration New Tables Added

Revision ID: 11576afdce05
Revises: 18b7cc3cb3c3
Create Date: 2025-09-29 12:29:12.079709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11576afdce05'
down_revision: Union[str, Sequence[str], None] = '18b7cc3cb3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('skill_weight', sa.Float(), nullable=False))
    op.add_column('job', sa.Column('experience_weight', sa.Float(), nullable=False))
    op.add_column('job', sa.Column('education_weight', sa.Float(), nullable=False))
    op.add_column('job', sa.Column('full_resume_weight', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'full_resume_weight')
    op.drop_column('job', 'education_weight')
    op.drop_column('job', 'experience_weight')
    op.drop_column('job', 'skill_weight')
    # ### end Alembic commands ###
