"""Initial migration New Tables

Revision ID: 18b7cc3cb3c3
Revises: e5749f83d4d8
Create Date: 2025-09-29 12:04:21.959107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18b7cc3cb3c3'
down_revision: Union[str, Sequence[str], None] = 'e5749f83d4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_job_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.candidate_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_job_match_id'), 'resume_job_match', ['id'], unique=False)
    op.add_column('resume_parsing', sa.Column('candidate_id', sa.Integer(), nullable=False))
    op.add_column('resume_parsing', sa.Column('job_id', sa.Integer(), nullable=False))
    op.add_column('resume_parsing', sa.Column('parsed_text', sa.Text(), nullable=True))
    op.add_column('resume_parsing', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'resume_parsing', 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resume_parsing', 'candidate', ['candidate_id'], ['candidate_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_parsing', type_='foreignkey')
    op.drop_constraint(None, 'resume_parsing', type_='foreignkey')
    op.drop_column('resume_parsing', 'created_at')
    op.drop_column('resume_parsing', 'parsed_text')
    op.drop_column('resume_parsing', 'job_id')
    op.drop_column('resume_parsing', 'candidate_id')
    op.drop_index(op.f('ix_resume_job_match_id'), table_name='resume_job_match')
    op.drop_table('resume_job_match')
    # ### end Alembic commands ###
