"""Initial migration New Migration

Revision ID: e733052ad4a5
Revises: 11576afdce05
Create Date: 2025-10-02 11:17:20.637044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e733052ad4a5'
down_revision: Union[str, Sequence[str], None] = '11576afdce05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resume_parsing_job_id_fkey'), 'resume_parsing', type_='foreignkey')
    op.drop_constraint(op.f('resume_parsing_candidate_id_fkey'), 'resume_parsing', type_='foreignkey')
    op.create_foreign_key(None, 'resume_parsing', 'candidate', ['candidate_id'], ['candidate_id'])
    op.create_foreign_key(None, 'resume_parsing', 'job', ['job_id'], ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume_parsing', type_='foreignkey')
    op.drop_constraint(None, 'resume_parsing', type_='foreignkey')
    op.create_foreign_key(op.f('resume_parsing_candidate_id_fkey'), 'resume_parsing', 'candidate', ['candidate_id'], ['candidate_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('resume_parsing_job_id_fkey'), 'resume_parsing', 'job', ['job_id'], ['job_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
